Add remote event show page [SSR-779]
homestars/que-web pull request #6
Opened 2021-11-08 22:41 UTC by hs-jkestenberg

Added a dynamic remote event show page that references all corresponding events.

2021-11-09 01:51 UTC, hs-arodrigues approved these changes, later dismissed
Awesome work, good idea on the view model for the remote event attributes!

2021-11-09 13:34 UTC, hs-psilva submitted a review, later dismissed

2021-11-09 13:51 UTC, gerrypower requested changes
Great work! One issue I would ask to fix as noted.

2021-11-09 13:51 UTC, gerrypower commented on lib/que/web/viewmodels/remote_event_abstract_attributes.rb
> +        "http://#{@remote_event.gateway.gsub('_', '-')}.homestars.#{tld}"
The `http` will break when we go to `https` which is part of the future plan. Sinatra knows, and maybe you just pass it to the class from the caller with `request.scheme`?

2021-11-09 17:42 UTC, gerrypower submitted a review, later dismissed

2021-11-22 21:20 UTC, hs-arodrigues approved these changes
Beautiful.

2021-11-22 21:33 UTC, merged